/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/~__root'
import { Route as AppLayoutRouteImport } from './routes/~app/~_layout'
import { Route as AppLayoutRoute2RouteImport } from './routes/~app/~_layout/~route2'
import { Route as AppLayoutRoute1RouteImport } from './routes/~app/~_layout/~route1'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutRoute2Route = AppLayoutRoute2RouteImport.update({
  id: '/route2',
  path: '/route2',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutRoute1Route = AppLayoutRoute1RouteImport.update({
  id: '/route1',
  path: '/route1',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppLayoutRouteWithChildren
  '/app/route1': typeof AppLayoutRoute1Route
  '/app/route2': typeof AppLayoutRoute2Route
}
export interface FileRoutesByTo {
  '/app': typeof AppLayoutRouteWithChildren
  '/app/route1': typeof AppLayoutRoute1Route
  '/app/route2': typeof AppLayoutRoute2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/route1': typeof AppLayoutRoute1Route
  '/app/_layout/route2': typeof AppLayoutRoute2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/app/route1' | '/app/route2'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/app/route1' | '/app/route2'
  id:
    | '__root__'
    | '/app'
    | '/app/_layout'
    | '/app/_layout/route1'
    | '/app/_layout/route2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_layout/route2': {
      id: '/app/_layout/route2'
      path: '/route2'
      fullPath: '/app/route2'
      preLoaderRoute: typeof AppLayoutRoute2RouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/route1': {
      id: '/app/_layout/route1'
      path: '/route1'
      fullPath: '/app/route1'
      preLoaderRoute: typeof AppLayoutRoute1RouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutRoute1Route: typeof AppLayoutRoute1Route
  AppLayoutRoute2Route: typeof AppLayoutRoute2Route
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutRoute1Route: AppLayoutRoute1Route,
  AppLayoutRoute2Route: AppLayoutRoute2Route,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
